services:
  - type: web
    name: fairscan-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "['http://localhost:3000', 'https://fairscan.web.app', 'https://fairscan-frontend.onrender.com']"
      - key: GCP_PROJECT
        value: fairscan-2026-8a945
      - key: VERTEX_AI_LOCATION
        value: asia-south1
      - key: FIREBASE_SERVICE_ACCOUNT
        value: /etc/secrets/serviceAccount.json
      - key: BIGQUERY_DATASET
        value: fairscan_analytics

  - type: web
    name: fairscan-frontend
    env: static
    buildCommand: bash ./frontend/build_flutter.sh
    staticPublishPath: ./frontend/build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
