import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'services/auth_service.dart';
import 'services/functions_service.dart';
import 'screens/home_screen.dart';
import 'screens/auth_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    // Replace these with values from your Firebase console
    // firebase_options.dart is auto-generated by: flutterfire configure
    options: const FirebaseOptions(
      apiKey:            "YOUR_API_KEY",
      authDomain:        "fairscan-2026.firebaseapp.com",
      projectId:         "fairscan-2026",
      storageBucket:     "fairscan-2026.appspot.com",
      messagingSenderId: "YOUR_SENDER_ID",
      appId:             "YOUR_APP_ID",
    ),
  );
  runApp(const FairScanApp());
}

class FairScanApp extends StatelessWidget {
  const FairScanApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthService()),
        Provider(create: (_) => FunctionsService()),
      ],
      child: MaterialApp(
        title: 'FairScan',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(
            seedColor: const Color(0xFF1D9E75),
          ),
          useMaterial3: true,
        ),
        home: const _AuthGate(),
      ),
    );
  }
}

class _AuthGate extends StatelessWidget {
  const _AuthGate();
  @override
  Widget build(BuildContext context) {
    final auth = context.watch<AuthService>();
    if (auth.isLoading) {
      return const Scaffold(body: Center(child: CircularProgressIndicator()));
    }
    return auth.user != null ? const HomeScreen() : const AuthScreen();
  }
}
